spring.application.name=spring-hw

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#postgres
spring.datasource.url=jdbc:postgresql://localhost:5450/spring_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.cloud.function.definition= consumer;producer;question;questionProcessor;answer;answerSout
spring.cloud.stream.kafka.binder.brokers= localhost:29092
spring.cloud.stream.kafka.binder.auto-create-topics=true
spring.cloud.stream.bindings.producer-out-0.destination= user-create-topic
spring.cloud.stream.bindings.consumer-in-0.destination= user-create-topic


spring.cloud.stream.bindings.question-out-0.destination=question-topic
spring.cloud.stream.bindings.questionProcessor-in-0.destination=question-topic
spring.cloud.stream.bindings.answer-out-0.destination=answer-topic
spring.cloud.stream.bindings.answerSout-in-0.destination=answer-topic