CREATE TABLE IF NOT EXISTS contacts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    middle_name VARCHAR(255),
    phone       VARCHAR(20)
);

INSERT INTO contacts (first_name, last_name, middle_name, phone)
VALUES ('Иван', 'Иванов', 'Иванович', '89121111111'),
       ('Петр', 'Петров', 'Петрович', '89122222222'),
       ('Мария', 'Сидорова', 'Алексеевна', '89123333333'),
       ('test_name', 'test_last_name', 'test_middle_name', '89129999999');